CREATE DATABASE DBCustomer;

USE DBCustomer;

CREATE TABLE CUSTOMERS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	GENDER CHAR(1) NOT NULL DEFAULT 'M',
	PHONE VARCHAR(20) NULL
);


CREATE TABLE ADDRESSES(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ADDRESS0 VARCHAR(MAX) NOT NULL,
	TYPE0 VARCHAR(20) NULL,
	CUSTOMERID INT NOT NULL,
	CONSTRAINT FK_CUSTOMERS_ADDRESSES FOREIGN KEY (CUSTOMERID)
	REFERENCES CUSTOMERS(ID)
);

